function cosmo_zeros2nans( filenames, eps )
%COSMO_ZEROS2NANS(filenames) 
%   change 0s to nans in a cell array of filenames generated by cosmomvpa
%   supports .nii and .gii files

for ii = 1:length(filenames)
    
    [~, ~, ext] = fileparts(filenames{ii});
    
    switch ext
        case '.nii'
           ds = cosmo_fmri_dataset(filenames{ii}); 
           ds.samples(abs(ds.samples) < eps) = nan;
           cosmo_map2fmri(ds,filenames{ii});
        case '.gii'
            ds = gifti(filenames{ii});
            ds.cdata(abs(ds.cdata) < eps) = nan;
            save(ds,filenames{ii});
    end
    
end


end

